== Setup Your Own Local OpenShift Server From Source

These files are used to build, start, and stop your own OpenShift environment from source:

[cols="1,1"]
|===
|Script Name|Description

|`env-openshift.sh`|Defines the OpenShift environment. Edit this so the variables are set to the appropriate values.
|`build-openshift.sh`|Downloads the OpenShift Origin source code and builds it.
|`cluster-openshift.sh`|Starts and stops your OpenShift Origin environment via "oc cluster up". Pass "up"/"down" to start/stop OpenShift.
|`start-openshift.sh`|Starts and stops your OpenShift Origin environment via "openshift". Pass "up"/"down" to start/stop OpenShift.
|`deploy-openshift-agent.sh`|Deploys the agent without requiring you to git clone the repository or build anything.
|===

To build your own OpenShift Origin:

1. Edit `env-openshift.sh` to set some of the variables to match your environment. Typically, you will leave most of this file the same, but you may want to edit the value of OPENSHIFT_GOPATH to point to a directory where you want the OpenShift Origin source to go. OPENSHIFT_IP_ADDRESS should pick up the IP address of your local machine, but if for some reason it does not, or if you want to use a different IP address, you may change the value of this variable to the custom IP address you want OpenShift Origin to bind to.

2. Run `build-openshift.sh` which will update the OpenShift Origin code to the latest version (cloning the git repository if it has not yet been downloaded to your filesystem) and then run the build.

3. Run `build-openshiftmetrics.sh` which will update the OpenShift Origin-Metrics code to the latest version (cloning the git repository if it has not yet been downloaded to your filesystem) and then run the build.

At this point, you have your own copy of OpenShift Origin and Origin-Metrics built. You can start and stop it using the `cluster-openshift.sh` script (which uses the "oc cluster" command):

* You can start it via: `cluster-openshift.sh up`
* You can stop it via: `cluster-openshift.sh down`
* You can get version and status information via: `cluster-openshift.sh status`

Or, alternatively, you can start and stop it using the `start-openshift.sh` script (which uses the "openshift" executable to start and will manually deploy Origin-Metrics and all its requirements).

* You can start it via: `start-openshift.sh up`
* You can stop it via: `start-openshift.sh down`
* You can get version and status information via: `start-openshift.sh status`

== Deploy the Agent

If you do not want to git clone the entire repository, just download the `deploy-openshift-agent.sh` script and run it. For more details about that script you can read the comments found at the top of that script.

If you git cloned the source repo, you can deploy the agent using the link:../Makefile[Makefile] located in the root directory of this project.

```
make openshift-deploy
```

If you want to build your own local docker image of the agent, you can use the "build docker" targets:

```
make build docker
```

Note that you must perform an initial "make build docker" before you can do a "make openshift-deploy" for the first time.

== Deploy Some Example Containers

To deploy the examples, use the Makefiles found in the link:../examples[examples].
