id: hawkular-openshift-agent
kind: ConfigMap
apiVersion: v1
name: Hawkular OpenShift Agent Configuration
metadata:
  name: hawkular-openshift-agent-configuration
  labels:
    metrics-infra: agent
data:
  config.yaml: |
    kubernetes:
      tenant: ${POD:namespace_name}
    hawkular_server:
      url: https://hawkular-metrics.openshift-infra.svc.cluster.local       
      credentials:
        username: secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.username
        password: secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.password
      ca_cert_file: secret:openshift-infra/hawkular-metrics-certificate/hawkular-metrics-ca.certificate
    emitter:
      status_enabled: true
    collector:
      max_metrics_per_pod: 50
      minimum_collection_interval: 10s
      default_collection_interval: 30s
      metric_id_prefix: pod/${POD:uid}/custom/
      pod_label_tags_prefix: labels.
      tags:
        metric_name: ${METRIC:name}
        description: ${METRIC:description}
        units: ${METRIC:units}
        namespace_id: ${POD:namespace_uid}
        namespace_name: ${POD:namespace_name}
        node_name: ${POD:node_name}
        pod_id: ${POD:uid}
        pod_ip: ${POD:ip}
        pod_name: ${POD:name}
        pod_namespace: ${POD:namespace_name}
        hostname: ${POD:hostname}
        host_ip: ${POD:host_ip}
        labels: ${POD:labels}
        cluster_name: ${POD:cluster_name}
        resource_version: ${POD:resource_version}
        type: pod
        collector: hawkular_openshift_agent
        custom_metric: true
  hawkular-openshift-agent: |
    endpoints:
    - type: prometheus
      protocol: "http"
      port: 8080
      path: /metrics
      collection_interval: 30s
