kind: ConfigMap
apiVersion: v1
metadata:
  name: jolokia-wildfly
data:
  hawkular-openshift-agent: |
    collection_interval_secs: 10
    endpoints:
    - type: jolokia
      protocol: "http"
      port: 8080
      path: /jolokia-war-1.3.5
      metrics:
      - name: java.lang:type=Threading#ThreadCount
        type: counter
        id:   VM Thread Count
      - name: java.lang:type=Memory#HeapMemoryUsage#used
        type: gauge
        id:   VM Heap Memory Used
